/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Second-v1.glb 
*/

import React, { useMemo } from "react";
import { useGLTF } from "@react-three/drei";
import { ConditionalMesh } from "../utils/conditionalMesh";
import * as THREE from "three";
import { Float } from "@react-three/drei";

export default function Model({ progress, loopCounter, ...props }) {
  const { nodes, materials } = useGLTF("/models/Second-v1.glb");

  // Create modified materials for even loops (grayscale and darker)
  const modifiedMaterials = useMemo(() => {
    if (loopCounter % 2 === 0) {
      const darkMaterials = {};
      Object.keys(materials).forEach((key) => {
        const material = materials[key].clone();

        // Just darken emissive colors (keep original colors but darker)
        const emissive = material.emissive;
        material.emissive.setRGB(
          emissive.r * 0.1, // Make it 40% darker
          emissive.g * 0.1,
          emissive.b * 0.1
        );

        darkMaterials[key] = material;
      });
      return darkMaterials;
    }
    return materials;
  }, [loopCounter, materials]);

  return (
    <group {...props} dispose={null}>
      <ConditionalMesh progress={progress} showRange={[0.64, 0.819]}>
        <group
          position={[3.235, 0.789, -22.545]}
          rotation={[0, 0.181, 0]}
          scale={0.14}
        >
          <mesh
            geometry={nodes.Cube012.geometry}
            material={modifiedMaterials["Bamboo Inner.001"]}
          />
          <mesh
            geometry={nodes.Cube012_1.geometry}
            material={modifiedMaterials["Bamboo.001"]}
          />
          <mesh
            geometry={nodes.Cube012_2.geometry}
            material={modifiedMaterials["Background.001"]}
          />
          <mesh
            geometry={nodes.Cube012_3.geometry}
            material={modifiedMaterials["Codrops Sushi Store.001"]}
          />
          <mesh
            geometry={nodes.Cube012_4.geometry}
            material={modifiedMaterials["Codrops Outline.001"]}
          />
          <mesh
            geometry={nodes.Cube012_5.geometry}
            material={modifiedMaterials["Egg White.001"]}
          />
          <mesh
            geometry={nodes.Cube012_6.geometry}
            material={modifiedMaterials["Egg yolk.001"]}
          />
          <mesh
            geometry={nodes.Cube012_7.geometry}
            material={modifiedMaterials["Miffy Outline.002"]}
          />
          <mesh
            geometry={nodes.Cube012_8.geometry}
            material={modifiedMaterials["Ramen Bowl.001"]}
          />
          <mesh
            geometry={nodes.Cube012_9.geometry}
            material={modifiedMaterials["Chopstick Black.001"]}
          />
          <mesh
            geometry={nodes.Cube012_10.geometry}
            material={modifiedMaterials["Material.001"]}
          />
          <mesh
            geometry={nodes.Cube012_11.geometry}
            material={modifiedMaterials["Chair Outline.001"]}
          />
          <mesh
            geometry={nodes.Cube012_12.geometry}
            material={modifiedMaterials["Noodles.001"]}
          />
          <mesh
            geometry={nodes.Cube012_13.geometry}
            material={modifiedMaterials["Wood board.001"]}
          />
          <mesh
            geometry={nodes.Cube012_14.geometry}
            material={modifiedMaterials["Pot.001"]}
          />
          <mesh
            geometry={nodes.Cube012_15.geometry}
            material={modifiedMaterials["Bamboo Outline.001"]}
          />
          <mesh
            geometry={nodes.Cube012_16.geometry}
            material={modifiedMaterials["Bamboo Shoot.003"]}
          />
          <mesh
            geometry={nodes.Cube012_17.geometry}
            material={modifiedMaterials["Grayish.001"]}
          />
          <mesh
            geometry={nodes.Cube012_18.geometry}
            material={modifiedMaterials["Vent.001"]}
          />
          <mesh
            geometry={nodes.Cube012_19.geometry}
            material={modifiedMaterials["Bamboo Brown.001"]}
          />
          <mesh
            geometry={nodes.Cube012_20.geometry}
            material={modifiedMaterials["Bamboo Inner Brown.001"]}
          />
          <mesh
            geometry={nodes.Cube012_21.geometry}
            material={modifiedMaterials["Dirt.001"]}
          />
        </group>
        {loopCounter % 2 !== 0 && (
          <group
            position={[3.235, 0.789, -22.545]}
            rotation={[0, 0.181, 0]}
            scale={0.14}
          >
            <mesh
              geometry={nodes.Cube013.geometry}
              material={modifiedMaterials["Codrops Outline.001"]}
            />
            <mesh
              geometry={nodes.Cube013_1.geometry}
              material={modifiedMaterials["Miffy Outline.002"]}
            />
            <mesh
              geometry={nodes.Cube013_2.geometry}
              material={modifiedMaterials["Wood board.001"]}
            />
            <mesh
              geometry={nodes.Cube013_3.geometry}
              material={modifiedMaterials["Soy Sauce label.001"]}
            />
            <mesh
              geometry={nodes.Cube013_4.geometry}
              material={modifiedMaterials["Soy sauce.001"]}
            />
            <mesh
              geometry={nodes.Cube013_5.geometry}
              material={modifiedMaterials["Paper.001"]}
            />
            <mesh
              geometry={nodes.Cube013_6.geometry}
              material={modifiedMaterials["Gray Pot.001"]}
            />
            <mesh
              geometry={nodes.Cube013_7.geometry}
              material={modifiedMaterials["Bowl.001"]}
            />
            <mesh
              geometry={nodes.Cube013_8.geometry}
              material={modifiedMaterials["Miffy Head.001"]}
            />
            <mesh
              geometry={nodes.Cube013_9.geometry}
              material={modifiedMaterials["Miffy Eyes.001"]}
            />
            <mesh
              geometry={nodes.Cube013_10.geometry}
              material={modifiedMaterials["Miffy Shirt.001"]}
            />
            <mesh
              geometry={nodes.Cube013_11.geometry}
              material={modifiedMaterials["Boris Black.001"]}
            />
            <mesh
              geometry={nodes.Cube013_12.geometry}
              material={modifiedMaterials["Hat.001"]}
            />
            <mesh
              geometry={nodes.Cube013_13.geometry}
              material={modifiedMaterials["Blue.001"]}
            />
            <mesh
              geometry={nodes.Cube013_14.geometry}
              material={modifiedMaterials["Bao Steamer.001"]}
            />
            <mesh
              geometry={nodes.Cube013_15.geometry}
              material={modifiedMaterials["Bao Steamer Outline.002"]}
            />
            <mesh
              geometry={nodes.Cube013_16.geometry}
              material={modifiedMaterials["Shusi Plate.001"]}
            />
            <mesh
              geometry={nodes.Cube013_17.geometry}
              material={modifiedMaterials["Chopstick.002"]}
            />
            <mesh
              geometry={nodes.Cube013_18.geometry}
              material={modifiedMaterials["Chopstick.003"]}
            />
            <mesh
              geometry={nodes.Cube013_19.geometry}
              material={modifiedMaterials["Rice.001"]}
            />
            <mesh
              geometry={nodes.Cube013_20.geometry}
              material={modifiedMaterials["Salmon.001"]}
            />
            <mesh
              geometry={nodes.Cube013_21.geometry}
              material={modifiedMaterials["Egg.001"]}
            />
            <mesh
              geometry={nodes.Cube013_22.geometry}
              material={modifiedMaterials["Onion.001"]}
            />
            <mesh
              geometry={nodes.Cube013_23.geometry}
              material={modifiedMaterials["Miffy Outline.003"]}
            />
            <mesh
              geometry={nodes.Cube013_24.geometry}
              material={modifiedMaterials["Shrimp.001"]}
            />
            <mesh
              geometry={nodes.Cube013_25.geometry}
              material={modifiedMaterials["Wasabi.001"]}
            />
            <mesh
              geometry={nodes.Cube013_26.geometry}
              material={modifiedMaterials["Wasabi Outline.001"]}
            />
            <mesh
              geometry={nodes.Cube013_27.geometry}
              material={modifiedMaterials["Red Cabbage.001"]}
            />
            <mesh
              geometry={nodes.Cube013_28.geometry}
              material={modifiedMaterials["Soy Sauce Holder.001"]}
            />
            <mesh
              geometry={nodes.Cube013_29.geometry}
              material={modifiedMaterials["Avocado.001"]}
            />
            <mesh
              geometry={nodes.Cube013_30.geometry}
              material={modifiedMaterials["Avocado Border.001"]}
            />
            <mesh
              geometry={nodes.Cube013_31.geometry}
              material={modifiedMaterials["Crab.001"]}
            />
            <mesh
              geometry={nodes.Cube013_32.geometry}
              material={modifiedMaterials["Seasmee Seed.001"]}
            />
            <mesh
              geometry={nodes.Cube013_33.geometry}
              material={modifiedMaterials["Bao Steamer Outline.003"]}
            />
          </group>
        )}
        <Float
          speed={1.5}
          rotationIntensity={0.2}
          floatIntensity={0.75}
          floatingRange={[-0.08, -0.15]}
        >
          <mesh
            geometry={nodes.Star_1.geometry}
            material={modifiedMaterials["Star.001"]}
            position={[2.624, 1.921, -22.485]}
            rotation={[0, 0.181, 0]}
            scale={0.14}
          />
        </Float>
        <Float
          speed={1.25}
          rotationIntensity={0.12}
          floatIntensity={1}
          floatingRange={[-0.2, 0.01]}
        >
          <mesh
            geometry={nodes.Star_2.geometry}
            material={modifiedMaterials["Star.001"]}
            position={[5.346, 2.367, -23.531]}
            rotation={[0, 0.181, 0]}
            scale={0.14}
          />
        </Float>
        <Float
          speed={1.6}
          rotationIntensity={0.14}
          floatIntensity={0.8}
          floatingRange={[-0.05, 0.05]}
        >
          <mesh
            geometry={nodes.Star_3.geometry}
            material={modifiedMaterials["Star.001"]}
            position={[5.485, 1.556, -23.264]}
            rotation={[0, 0.181, 0]}
            scale={0.14}
          />
        </Float>
        {loopCounter % 2 !== 0 && (
          <group
            position={[3.235, 0.789, -22.545]}
            rotation={[0, 0.181, 0]}
            scale={0.14}
          >
            <mesh
              geometry={nodes.Cube020.geometry}
              material={modifiedMaterials["Pusheen Outline.001"]}
            />
            <mesh
              geometry={nodes.Cube020_1.geometry}
              material={modifiedMaterials["Pusheen Body.001"]}
            />
            <mesh
              geometry={nodes.Cube020_2.geometry}
              material={modifiedMaterials["Pusheen Eyes.001"]}
            />
          </group>
        )}

        {loopCounter % 2 === 0 && (
          <group
            position={[3.263, 0.645, -22.079]}
            rotation={[0, -0.82, 0]}
            scale={1.176}
          >
            <mesh
              geometry={nodes.Plane.geometry}
              material={modifiedMaterials["Pusheen Body.001"]}
            />
            <mesh
              geometry={nodes.Plane_1.geometry}
              material={modifiedMaterials["Pusheen Outline.001"]}
            />
            <mesh
              geometry={nodes.Plane_2.geometry}
              material={modifiedMaterials["Pusheen Eyes.001"]}
            />
          </group>
        )}
      </ConditionalMesh>
    </group>
  );
}

useGLTF.preload("/models/Second-v1.glb");
